// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: news/v1/service.proto

package newsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_news_v1_service_proto protoreflect.FileDescriptor

const file_news_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15news/v1/service.proto\x12\anews.v1\x1a\x12news/v1/news.proto2z\n" +
	"\vNewsService\x129\n" +
	"\x06Create\x12\x16.news.v1.CreateRequest\x1a\x17.news.v1.CreateResponse\x120\n" +
	"\x03Get\x12\x13.news.v1.GetRequest\x1a\x14.news.v1.GetResponseB\x8e\x01\n" +
	"\vcom.news.v1B\fServiceProtoP\x01Z4github.com/sanjevscet/news-grpc/proto/news/v1;newsv1\xa2\x02\x03NXX\xaa\x02\aNews.V1\xca\x02\aNews\\V1\xe2\x02\x13News\\V1\\GPBMetadata\xea\x02\bNews::V1b\x06proto3"

var file_news_v1_service_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: news.v1.CreateRequest
	(*GetRequest)(nil),     // 1: news.v1.GetRequest
	(*CreateResponse)(nil), // 2: news.v1.CreateResponse
	(*GetResponse)(nil),    // 3: news.v1.GetResponse
}
var file_news_v1_service_proto_depIdxs = []int32{
	0, // 0: news.v1.NewsService.Create:input_type -> news.v1.CreateRequest
	1, // 1: news.v1.NewsService.Get:input_type -> news.v1.GetRequest
	2, // 2: news.v1.NewsService.Create:output_type -> news.v1.CreateResponse
	3, // 3: news.v1.NewsService.Get:output_type -> news.v1.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_news_v1_service_proto_init() }
func file_news_v1_service_proto_init() {
	if File_news_v1_service_proto != nil {
		return
	}
	file_news_v1_news_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_v1_service_proto_rawDesc), len(file_news_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_news_v1_service_proto_goTypes,
		DependencyIndexes: file_news_v1_service_proto_depIdxs,
	}.Build()
	File_news_v1_service_proto = out.File
	file_news_v1_service_proto_goTypes = nil
	file_news_v1_service_proto_depIdxs = nil
}
